hydra:
  run:
    dir: /public/home/xinwuye/ai4s-tool-joint-train/runs/pocket_prefix_supervised_smoke/${now:%Y%m%d_%H%M%S}
  job:
    chdir: True

model_variant: pocket_prefix_mm

multimodal:
  init_unimodal_ckpt: /public/home/xinwuye/ai4s-tool-joint-train/genmol/checkpoints/genmol_v2_v1.0/model_v2.ckpt

multimodal_data:
  crossdocked_lmdb_path: /public/home/xinwuye/ai4s-tool-joint-train/runs/pocket_prefix/data/gdrive_exact_only/crossdocked_v1.1_rmsd1.0_pocket10_processed_final.lmdb
  crossdocked_split_path: /public/home/xinwuye/ai4s-tool-joint-train/runs/pocket_prefix/data/gdrive_exact_only/crossdocked_pocket10_pose_split.pt
  manifest_path: /public/home/xinwuye/ai4s-tool-joint-train/runs/pocket_prefix/data/gdrive_exact_only/crossdocked_pocket10_pocket_prefix_manifest.pt
  split: train

wandb:
  project: genmol
  name: pocket-prefix-supervised-smoke

loader:
  global_batch_size: 32
  batch_size: ${div_up:${.global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
  num_workers: 4
  pin_memory: True

optim:
  weight_decay: 0
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8

trainer:
  _target_: lightning.Trainer
  accelerator: cuda
  num_nodes: 1
  devices: 2
  accumulate_grad_batches: ${div_up:${loader.global_batch_size}, ${eval:${trainer.devices} * ${loader.batch_size} * ${trainer.num_nodes}}}
  gradient_clip_val: 1.0
  precision: bf16
  max_steps: 10
  log_every_n_steps: 1

model:
  attention_probs_dropout_prob: 0.1
  classifier_dropout: null
  hidden_act: gelu
  hidden_dropout_prob: 0.1
  hidden_size: 768
  initializer_range: 0.02
  intermediate_size: 3072
  layer_norm_eps: 1e-12
  max_position_embeddings: 256
  model_type: bert
  num_attention_heads: 12
  num_hidden_layers: 12
  pad_token_id: 3
  position_embedding_type: absolute
  torch_dtype: float32
  type_vocab_size: 2
  use_cache: True
  vocab_size: 1882

conditioning:
  max_total_positions: 256
  overlength_policy: drop_sample
  projector_type: mlp2

pocket_encoder:
  name: esm_if_official
  freeze: true
  mode: online
  model_name: esm_if1_gvp4_t16_142M_UR50

training:
  T: 0
  ema: 0.9999
  antithetic_sampling: True
  sampling_eps: 1e-3
  global_mean_loss: True
  use_bracket_safe: False

callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${cwd:}/checkpoints
  filename: '{step}'
  save_top_k: -1
  auto_insert_metric_name: False
  enable_version_counter: False
  every_n_train_steps: 5
